# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://talos-crypto.github.io/
title: Talos
email: your-email@domain.com
author: Talos Team
description: Talos gives users back control over their data while still allowing applications to harness the power of the cloud.

copyright: 'Copyright &copy; 2016, <a href="http://www.vs.inf.ethz.ch/">Distributed Systems Group</a>, <a href="https://www.ethz.ch/">ETH Zurich</a>'
credits: 'Credits: Landing Page theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
safe: true #mimicks Github settings
gems:
  - jekyll-sitemap

# Build settings
markdown: redcarpet
permalink: /:title/

# These settings will match the markdown language to be pretty much exactly the same as "Github Flavoured Markdown" 
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks", "lax_spacing" ]